camera: mv

odom2camera:
  # xyz: "\"0.12 0.0  0.090\""
  xyz: "\"0 -0.04  0.104\""
  # xyz: "\"0.12 0.0  0.090\""
  rpy: "\" 0  0.0 0.0\""  #0.01

detector_log_level: INFO
tracker_log_level: INFO
serial_log_level: INFO

#  xyz: "\"0.12 0.0  0.090\""
#  xyz: "\"0.12 0.0  0.090\""
#  xyz: "\"0.12 0.0  0.090\""